
kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: golang
    commands:
      - echo ${TEST_ENV}
      - echo ${{TEST_ENV}}
      - echo ${GITHUB_SHA}
      - echo $GITHUB_SHA
